name: documentation-builder
version: '1.7.0'
base: core18
summary: Build HTML documentation from markdown
description: |
  A tool to build repositories of markdown files of documentation into HTML pages

grade: stable
confinement: strict

parts:
  repo:
    plugin: python
    source: .
    stage-packages:
      - git
  copy:
    plugin: dump
    source: .

apps:
  documentation-builder:
    plugs:
      - home
    command: documentation-builder
